# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patternwidget.ui'
#
# Created: Fri Feb  1 18:00:42 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PatternWidget(object):
    def setupUi(self, PatternWidget):
        PatternWidget.setObjectName(_fromUtf8("PatternWidget"))
        PatternWidget.resize(616, 78)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PatternWidget.sizePolicy().hasHeightForWidth())
        PatternWidget.setSizePolicy(sizePolicy)
        PatternWidget.setMinimumSize(QtCore.QSize(550, 78))
        PatternWidget.setMaximumSize(QtCore.QSize(16777215, 78))
        PatternWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        PatternWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.mainLayout = QtGui.QHBoxLayout(PatternWidget)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setMargin(0)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.MainFrame = QtGui.QFrame(PatternWidget)
        self.MainFrame.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.MainFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.MainFrame.setObjectName(_fromUtf8("MainFrame"))
        self.PatternStripLayout = QtGui.QHBoxLayout(self.MainFrame)
        self.PatternStripLayout.setSpacing(0)
        self.PatternStripLayout.setContentsMargins(2, 0, 2, 0)
        self.PatternStripLayout.setObjectName(_fromUtf8("PatternStripLayout"))
        self.DataFrame = QtGui.QWidget(self.MainFrame)
        self.DataFrame.setMinimumSize(QtCore.QSize(316, 0))
        self.DataFrame.setMaximumSize(QtCore.QSize(316, 16777215))
        self.DataFrame.setObjectName(_fromUtf8("DataFrame"))
        self.TempoScaleSpinBox = QtGui.QDoubleSpinBox(self.DataFrame)
        self.TempoScaleSpinBox.setEnabled(False)
        self.TempoScaleSpinBox.setGeometry(QtCore.QRect(215, 39, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TempoScaleSpinBox.setFont(font)
        self.TempoScaleSpinBox.setDecimals(1)
        self.TempoScaleSpinBox.setMinimum(10.0)
        self.TempoScaleSpinBox.setMaximum(600.0)
        self.TempoScaleSpinBox.setProperty("value", 120.0)
        self.TempoScaleSpinBox.setObjectName(_fromUtf8("TempoScaleSpinBox"))
        self.ToLabel = QtGui.QLabel(self.DataFrame)
        self.ToLabel.setEnabled(False)
        self.ToLabel.setGeometry(QtCore.QRect(92, 51, 16, 16))
        self.ToLabel.setObjectName(_fromUtf8("ToLabel"))
        self.LastBarLbl = QtGui.QLabel(self.DataFrame)
        self.LastBarLbl.setEnabled(False)
        self.LastBarLbl.setGeometry(QtCore.QRect(105, 51, 31, 16))
        self.LastBarLbl.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.LastBarLbl.setFrameShape(QtGui.QFrame.Box)
        self.LastBarLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LastBarLbl.setObjectName(_fromUtf8("LastBarLbl"))
        self.BarSpinBox = QtGui.QSpinBox(self.DataFrame)
        self.BarSpinBox.setGeometry(QtCore.QRect(28, 1, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.BarSpinBox.setFont(font)
        self.BarSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BarSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BarSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.BarSpinBox.setMinimum(1)
        self.BarSpinBox.setMaximum(999)
        self.BarSpinBox.setProperty("value", 1)
        self.BarSpinBox.setObjectName(_fromUtf8("BarSpinBox"))
        self.MeterCustomBtn = QtGui.QPushButton(self.DataFrame)
        self.MeterCustomBtn.setGeometry(QtCore.QRect(143, 0, 16, 71))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setKerning(True)
        self.MeterCustomBtn.setFont(font)
        self.MeterCustomBtn.setCheckable(True)
        self.MeterCustomBtn.setChecked(False)
        self.MeterCustomBtn.setObjectName(_fromUtf8("MeterCustomBtn"))
        self.TempoMainSpinBox = QtGui.QDoubleSpinBox(self.DataFrame)
        self.TempoMainSpinBox.setGeometry(QtCore.QRect(215, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TempoMainSpinBox.setFont(font)
        self.TempoMainSpinBox.setDecimals(1)
        self.TempoMainSpinBox.setMinimum(10.0)
        self.TempoMainSpinBox.setMaximum(600.0)
        self.TempoMainSpinBox.setProperty("value", 120.0)
        self.TempoMainSpinBox.setObjectName(_fromUtf8("TempoMainSpinBox"))
        self.MainEnabledBtn = QtGui.QPushButton(self.DataFrame)
        self.MainEnabledBtn.setGeometry(QtCore.QRect(8, 0, 16, 71))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setKerning(True)
        self.MainEnabledBtn.setFont(font)
        self.MainEnabledBtn.setCheckable(True)
        self.MainEnabledBtn.setChecked(True)
        self.MainEnabledBtn.setObjectName(_fromUtf8("MainEnabledBtn"))
        self.AccentsDefBtn = QtGui.QPushButton(self.DataFrame)
        self.AccentsDefBtn.setGeometry(QtCore.QRect(301, 0, 16, 71))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setKerning(True)
        self.AccentsDefBtn.setFont(font)
        self.AccentsDefBtn.setCheckable(True)
        self.AccentsDefBtn.setObjectName(_fromUtf8("AccentsDefBtn"))
        self.Div2 = QtGui.QFrame(self.DataFrame)
        self.Div2.setGeometry(QtCore.QRect(211, 1, 4, 71))
        self.Div2.setFrameShape(QtGui.QFrame.VLine)
        self.Div2.setFrameShadow(QtGui.QFrame.Sunken)
        self.Div2.setObjectName(_fromUtf8("Div2"))
        self.FromLbl = QtGui.QLabel(self.DataFrame)
        self.FromLbl.setEnabled(False)
        self.FromLbl.setGeometry(QtCore.QRect(30, 51, 31, 16))
        self.FromLbl.setObjectName(_fromUtf8("FromLbl"))
        self.MeterNumSpinBox = QtGui.QSpinBox(self.DataFrame)
        self.MeterNumSpinBox.setEnabled(False)
        self.MeterNumSpinBox.setGeometry(QtCore.QRect(158, 1, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.MeterNumSpinBox.setFont(font)
        self.MeterNumSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MeterNumSpinBox.setMinimum(1)
        self.MeterNumSpinBox.setMaximum(32)
        self.MeterNumSpinBox.setProperty("value", 4)
        self.MeterNumSpinBox.setObjectName(_fromUtf8("MeterNumSpinBox"))
        self.DivMeter = QtGui.QFrame(self.DataFrame)
        self.DivMeter.setGeometry(QtCore.QRect(158, 27, 51, 16))
        self.DivMeter.setFrameShape(QtGui.QFrame.HLine)
        self.DivMeter.setFrameShadow(QtGui.QFrame.Sunken)
        self.DivMeter.setObjectName(_fromUtf8("DivMeter"))
        self.FirstBarLbl = QtGui.QLabel(self.DataFrame)
        self.FirstBarLbl.setEnabled(False)
        self.FirstBarLbl.setGeometry(QtCore.QRect(60, 51, 31, 16))
        self.FirstBarLbl.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.FirstBarLbl.setFrameShape(QtGui.QFrame.Box)
        self.FirstBarLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FirstBarLbl.setObjectName(_fromUtf8("FirstBarLbl"))
        self.Div1 = QtGui.QFrame(self.DataFrame)
        self.Div1.setGeometry(QtCore.QRect(138, 1, 4, 71))
        self.Div1.setFrameShape(QtGui.QFrame.VLine)
        self.Div1.setFrameShadow(QtGui.QFrame.Sunken)
        self.Div1.setObjectName(_fromUtf8("Div1"))
        self.Div3 = QtGui.QFrame(self.DataFrame)
        self.Div3.setGeometry(QtCore.QRect(296, 1, 4, 71))
        self.Div3.setFrameShape(QtGui.QFrame.VLine)
        self.Div3.setFrameShadow(QtGui.QFrame.Sunken)
        self.Div3.setObjectName(_fromUtf8("Div3"))
        self.MeterDenSpinBox = QtGui.QSpinBox(self.DataFrame)
        self.MeterDenSpinBox.setEnabled(False)
        self.MeterDenSpinBox.setGeometry(QtCore.QRect(158, 38, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.MeterDenSpinBox.setFont(font)
        self.MeterDenSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MeterDenSpinBox.setMinimum(1)
        self.MeterDenSpinBox.setMaximum(128)
        self.MeterDenSpinBox.setProperty("value", 4)
        self.MeterDenSpinBox.setObjectName(_fromUtf8("MeterDenSpinBox"))
        self.line = QtGui.QFrame(self.DataFrame)
        self.line.setGeometry(QtCore.QRect(3, 0, 3, 70))
        self.line.setFrameShadow(QtGui.QFrame.Raised)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.TempoChangeCombo = QtGui.QComboBox(self.DataFrame)
        self.TempoChangeCombo.setGeometry(QtCore.QRect(215, 27, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.TempoChangeCombo.setFont(font)
        self.TempoChangeCombo.setObjectName(_fromUtf8("TempoChangeCombo"))
        self.TempoChangeCombo.addItem(_fromUtf8(""))
        self.TempoChangeCombo.addItem(_fromUtf8(""))
        self.PatternStripLayout.addWidget(self.DataFrame)
        self.BeatsFrame = QtGui.QWidget(self.MainFrame)
        self.BeatsFrame.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BeatsFrame.sizePolicy().hasHeightForWidth())
        self.BeatsFrame.setSizePolicy(sizePolicy)
        self.BeatsFrame.setMinimumSize(QtCore.QSize(160, 0))
        self.BeatsFrame.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.BeatsFrame.setObjectName(_fromUtf8("BeatsFrame"))
        self.BeatsLayout = QtGui.QHBoxLayout(self.BeatsFrame)
        self.BeatsLayout.setSpacing(0)
        self.BeatsLayout.setMargin(0)
        self.BeatsLayout.setMargin(0)
        self.BeatsLayout.setObjectName(_fromUtf8("BeatsLayout"))
        self.PatternStripLayout.addWidget(self.BeatsFrame)
        self.VolumeFrame = QtGui.QWidget(self.MainFrame)
        self.VolumeFrame.setMinimumSize(QtCore.QSize(58, 0))
        self.VolumeFrame.setMaximumSize(QtCore.QSize(58, 16777215))
        self.VolumeFrame.setObjectName(_fromUtf8("VolumeFrame"))
        self.VolSpinBox = QtGui.QDoubleSpinBox(self.VolumeFrame)
        self.VolSpinBox.setGeometry(QtCore.QRect(5, 24, 51, 22))
        self.VolSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VolSpinBox.setDecimals(1)
        self.VolSpinBox.setSingleStep(0.1)
        self.VolSpinBox.setProperty("value", 1.0)
        self.VolSpinBox.setObjectName(_fromUtf8("VolSpinBox"))
        self.VolDefBtn = QtGui.QPushButton(self.VolumeFrame)
        self.VolDefBtn.setGeometry(QtCore.QRect(5, 2, 51, 22))
        self.VolDefBtn.setCheckable(True)
        self.VolDefBtn.setObjectName(_fromUtf8("VolDefBtn"))
        self.VolMuteBtn = QtGui.QPushButton(self.VolumeFrame)
        self.VolMuteBtn.setGeometry(QtCore.QRect(5, 47, 51, 22))
        self.VolMuteBtn.setCheckable(True)
        self.VolMuteBtn.setChecked(False)
        self.VolMuteBtn.setObjectName(_fromUtf8("VolMuteBtn"))
        self.Div4 = QtGui.QFrame(self.VolumeFrame)
        self.Div4.setGeometry(QtCore.QRect(0, 0, 4, 71))
        self.Div4.setFrameShape(QtGui.QFrame.VLine)
        self.Div4.setFrameShadow(QtGui.QFrame.Sunken)
        self.Div4.setObjectName(_fromUtf8("Div4"))
        self.PatternStripLayout.addWidget(self.VolumeFrame)
        self.mainLayout.addWidget(self.MainFrame)
        self.actionAggiungi = QtGui.QAction(PatternWidget)
        self.actionAggiungi.setObjectName(_fromUtf8("actionAggiungi"))

        self.retranslateUi(PatternWidget)
        self.TempoChangeCombo.setCurrentIndex(0)
        QtCore.QObject.connect(self.AccentsDefBtn, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.BeatsFrame.setEnabled)
        QtCore.QObject.connect(self.MeterCustomBtn, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.MeterNumSpinBox.setEnabled)
        QtCore.QObject.connect(self.MeterCustomBtn, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.MeterDenSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(PatternWidget)

    def retranslateUi(self, PatternWidget):
        PatternWidget.setWindowTitle(QtGui.QApplication.translate("PatternWidget", "Pattern", None, QtGui.QApplication.UnicodeUTF8))
        self.ToLabel.setText(QtGui.QApplication.translate("PatternWidget", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.MeterCustomBtn.setText(QtGui.QApplication.translate("PatternWidget", "D\n"
"E\n"
"F\n"
"A\n"
"U\n"
"L\n"
"T", None, QtGui.QApplication.UnicodeUTF8))
        self.MainEnabledBtn.setText(QtGui.QApplication.translate("PatternWidget", "E\n"
"N\n"
"A\n"
"B\n"
"L\n"
"E\n"
"D", None, QtGui.QApplication.UnicodeUTF8))
        self.AccentsDefBtn.setText(QtGui.QApplication.translate("PatternWidget", "D\n"
"E\n"
"F\n"
"A\n"
"U\n"
"L\n"
"T", None, QtGui.QApplication.UnicodeUTF8))
        self.FromLbl.setText(QtGui.QApplication.translate("PatternWidget", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.TempoChangeCombo.setItemText(0, QtGui.QApplication.translate("PatternWidget", "F I X E D", None, QtGui.QApplication.UnicodeUTF8))
        self.TempoChangeCombo.setItemText(1, QtGui.QApplication.translate("PatternWidget", "SCALED", None, QtGui.QApplication.UnicodeUTF8))
        self.VolDefBtn.setText(QtGui.QApplication.translate("PatternWidget", "DEFAULT", None, QtGui.QApplication.UnicodeUTF8))
        self.VolMuteBtn.setText(QtGui.QApplication.translate("PatternWidget", "MUTE", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAggiungi.setText(QtGui.QApplication.translate("PatternWidget", "Aggiungi", None, QtGui.QApplication.UnicodeUTF8))


class PatternWidget(QtGui.QWidget, Ui_PatternWidget):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QWidget.__init__(self, parent, f)

        self.setupUi(self)

